FROM golang:1.15-alpine

ENV GOPATH /app
ENV GOOS linux

RUN apk add --no-cache bash git openssh gcc libc-dev \
    && mkdir -p /app/src/github.com/darkweak/cmd && mkdir -p /app/src/github.com/darkweak/souin

WORKDIR /app/src/github.com/darkweak/souin

ADD ./souin/go.* /app/src/github.com/darkweak/souin/
RUN go mod download && GO111MODULE=on go get -d golang.org/x/lint/golint && go install golang.org/x/lint/golint

ADD ./souin/api /app/src/github.com/darkweak/souin/api
ADD ./souin/cache /app/src/github.com/darkweak/souin/cache
ADD ./souin/tests /app/src/github.com/darkweak/souin/tests
ADD ./souin/rfc /app/src/github.com/darkweak/souin/rfc
ADD ./souin/configuration /app/src/github.com/darkweak/souin/configuration
ADD ./souin/configurationtypes /app/src/github.com/darkweak/souin/configurationtypes
ADD ./souin/default /app/src/github.com/darkweak/souin/default
ADD ./souin/errors /app/src/github.com/darkweak/souin/errors
ADD ./souin/helpers /app/src/github.com/darkweak/souin/helpers
ADD ./souin/providers /app/src/github.com/darkweak/souin/providers
ADD ./souin/plugins /app/src/github.com/darkweak/souin/plugins

RUN go mod download

EXPOSE 80

CMD ["go", "run", "plugins/souin/main.go"]
